s/\b_GLIBCXX_BEGIN_NAMESPACE_VERSION//g
s/\b_GLIBCXX_BEGIN_NAMESPACE_ALGO//g
s///g
s/ / /g
s/ / /g
s/\b_GLIBCXX_BEGIN_NAMESPACE_CONTAINER//g
s/_GLIBCXX_BEGIN_NESTED_NAMESPACE\s*\(\s*std\s*,\s*_GLIBCXX_STD_[DP]\s*\)/namespace std{/g
s/\b_GLIBCXX_END_NAMESPACE_VERSION\b//g
s/\b_GLIBCXX_END_NAMESPACE_CONTAINER\b//g
s///g
s///g
s/\b_GLIBCXX_END_(NESTED_\?NAMESPACE\b/}/g
